#pragma config(Sensor, in1,    taylorsstoned,  sensorPotentiometer)
#pragma config(Sensor, in2,    powerex,        sensorNone)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  REncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LEncoder,       sensorQuadEncoder)
#pragma config(Motor,  port1,           cata1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           R1,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           R2,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           L1,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           L2,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          cata2,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define vexCompetitionState (nVexRCReceiveState & (vrDisabled | vrAutonomousMode))
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(150)
#include "VEX_Competition_Includes.c"

float in = 360/(3.14159265358979*4);

void moveBack(int ticks){
	SensorValue[REncoder] = 0;
	SensorValue[LEncoder] = 0;
	while(SensorValue[LEncoder] <= ticks && SensorValue[REncoder] <= ticks){
		if(SensorValue[LEncoder] <= ticks){
			motor[L1] = -127;
			motor[L2] = -127;
		}
		if(SensorValue[REncoder] <= ticks){
			motor[R1] = -127;
			motor[R2] = -127;
		}
	}
	motor[L1] = 0;
	motor[L2] = 0;
	motor[R1] = 0;
	motor[R2] = 0;
}
void move(int ticks){
	SensorValue[REncoder] = 0;
	SensorValue[LEncoder] = 0;
	while(SensorValue[LEncoder] >= -1*ticks && SensorValue[REncoder] >= -1*ticks){
		if(SensorValue[LEncoder] >= -1*ticks){
			motor[L1] = 127;
			motor[L2] = 127;
		}
		if(SensorValue[REncoder] >= -1*ticks){
			motor[R1] = 127;
			motor[R2] = 127;
		}
	}
	motor[L1] = 0;
	motor[L2] = 0;
	motor[R1] = 0;
	motor[R2] = 0;
}
void intakeOn(){
	motor[intake] = 100;
}
void intakeOff(){
	motor[intake] = 0;
}
void spinRight(int deg10){
	SensorValue[gyro] = 0;
	while(abs(SensorValue[gyro]) < deg10){
		motor[L1] = 100;
		motor[L2] = 100;
	}
	motor[L1] = 0;
	motor[L2] = 0;
}
void spinLeft(int deg10){
	SensorValue[gyro] = 0;
	while(abs(SensorValue[gyro]) < deg10){
		motor[R1] = 100;
		motor[R2] = 100;
	}
	motor[R1] = 0;
	motor[R2] = 0;
}
void shoot(){
	motor[cata1] = 100;
	motor[cata2] = 100;
	wait(1000);
	motor[cata1] = 0;
	motor[cata2] = 0;
}
void pre_auton(){
}
task autonomous ()
{

	//RED SIDE - Auto 1 -----------------------------------------------------

	//Step 1: Turn on intake and drive forward
	intakeOn();
	move(500);
	//Step 2: Turn off intake and drive back same amount
	intakeOff();
	moveBack(500);
	//Step 3: Turn 90deg left
	spinLeft(900);
	//Step 4: Move forward slightly
	move(100);
	//Step 5: Shoot catapult
	shoot();
	//Step 6: Drive forward to hit low flag
	move(400);
	//Step 7: Move back slightly
	moveBack(200);
	//Step 8: Turn right 45deg
	spinRight(450);
	//Step 9: Move forward
	move(350);

	//Skills Auto-------------------------------------------------------

	//Step 1: Turn on intake and drive forward
	intakeOn();
	move(500);
	//Step 2: Turn off intake and drive back same amount
	intakeOff();
	moveBack(500);
	//Step 3: Turn 90deg left
	spinLeft(900);
	//Step 4: Move forward slightly
	move(100);
	//Step 5: Shoot
	shoot();
	//Step 6: Drive forward to hit low flag
	move(400);
	//Step 7: Move back slightly
	moveBack(200);
	//Step 8: Turn right 90deg
	spinRight(90);
	//Step 9: Flip over
	//Step 10: Back up slightly and turn 45deg left
	moveBack(200);
	spinLeft(450);
	//Step 11: Forward
	move(300);

}
task usercontrol()
{
	//This whole block is dedicated to displaying the Battery Voltage on the LCD Display
	bLCDBacklight = true;									// Turn on LCD Backlight
	string mainBattery;
	string secondaryBattery;
	clearLCDLine(0);											// Clear line 1 (0) of the LCD
	clearLCDLine(1);											// Clear line 2 (1) of the LCD

	//Display the Primary Robot battery voltage
	displayLCDString(0, 0, "Primary: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
	displayNextLCDString(mainBattery);

	//Display the Secondary Robot battery voltage
	displayLCDString(1, 0, "Secondary: ");
	sprintf(secondaryBattery, "%1.2f%c", SensorValue(powerex)/275, 'V');
	displayNextLCDString(secondaryBattery);

	//Short delay for the LCD refresh rate
	wait1Msec(100);

	while (1==1){
		//Right joystick controls right wheels
		motor[R1] = vexRT[Ch2]*0.5;
		motor[R2] = vexRT[Ch2]*0.5;
		//Left joystick controls left wheels
		motor[L1] = vexRT[Ch3]*0.5;
    motor[L2] = vexRT[Ch3]*0.5;
		//Sending 50% power to prevent overheating in the motors

    if(vexRT[Btn6U] && SensorValue[taylorsstoned] > 100){
			motor[cata1] = 100;
			motor[cata2] = 100;
		}
		else{
			motor[cata1] = 0;
			motor[cata2] = 0;
		}

		if(vexRT[Btn6D]){
			motor[cata1] = 100;
			motor[cata2] = 100;
		}
		else{
			motor[cata1] = 0;
			motor[cata2] = 0;
		}

		if(vexRT[Btn5U]){
			motor[intake] = 100;
		}
		else{
			motor[intake] = 0;
		}

		if(vexRT[Btn5U]){
			motor[intake] = 100;
		}
		else{
			motor[intake] = 0;
		}

		if(vexRT[Btn5D]){
			startTask(autonomous);
			wait1Msec(6000);
			stopTask(autonomous);
		}
		/* press the bottom button of the right buttons to
		start the autonomous*/
	}
}
